steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/avroparserapplication/avroparserimage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/avroparserapplication/avroparserimage']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'avroparserservice', '--image', 'gcr.io/avroparserapplication/avroparserimage', '--region', 'europe-west1', '--platform', 'managed']
images:
- gcr.io/avroparserapplication/avroparserimage